services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  backend:
    build: .
    container_name: backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`webapp.local`)"
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    networks:
      - api
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - api
    volumes:
      - pgData:/data/db
      - ./data/postgres:/var/lib/postgresql

volumes:
  pgData:

networks:
  api: