services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    networks:
      - api
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - api
    volumes:
      - pgData:/data/db
      - ./data/postgres:/var/lib/postgresql

volumes:
  pgData:

networks:
  api: