apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 50

